###########################################
# Spring Application Properties
###########################################
spring.application.name=crud.wefblux
server.port=9091
###########################################
# DataBase Properties
###########################################
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/crud_db
spring.r2dbc.username=local
spring.r2dbc.password=postgres